version: '3'

services: 

  nginx:
    build:
      context: ./nginx
    image: diegofmatos/nginx:challenge
    container_name: nginx
    restart: unless-stopped
    networks:
      - node-network
    ports:
      - '3000:80'
    depends_on:
      - app

  app:
    build: 
      context: ./node
    image: diegofmatos/app:challenge
    container_name: app
    restart: always
    command: node index.js
    entrypoint: dockerize -wait tcp://db:3306 -timeout 20s docker-entrypoint.sh
    networks: 
      - node-network
#    volumes: 
#      - ./app
    tty: true
    depends_on: 
       - db

  db:
    image: mysql:5.7
    command: --innodb-use-native-aio=0
    container_name: mysql
    restart: always
    tty: true
    volumes: 
      - ./mysql:/var/lib/mysql
      - ./schema:/docker-entrypoint-initdb.d
    environment: 
      - MYSQL_DATABASE=nodedb
      - MYSQL_ROOT_PASSWORD=root
    networks: 
      - node-network

networks: 
  node-network:
    driver: bridge